<?php

namespace App\Livewire;

use App\Models\Service;
use App\Models\Booking;
use App\Services\BookingService;
use Livewire\Component;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;

class CreateBooking extends Component
{
    public $step = 1;
    public $services;
    public $selectedService;
    public $numberOfPeople = 1;
    public $selectedDate;
    public $referenceCode;
    public $qrCode;
    public $paymentMethod;
    public $orderRef;
    
    protected $bookingService;

    public function boot(BookingService $bookingService)
    {
        $this->bookingService = $bookingService;
    }

    public function mount()
    {
        $this->services = Service::where('is_active', true)->get();
    }

    public function selectService($serviceId)
    {
        $this->selectedService = $serviceId;
        $this->step = 2;
    }

    public function selectNumberOfPeople($number)
    {
        $this->numberOfPeople = $number;
        $this->step = 3;
    }

    public function selectDate($date)
    {
        $this->selectedDate = $date;
        // Skip loading slots and go directly to payment method
        $this->step = 4;
    }
    
    public function handleDateSelection()
    {
        if ($this->selectedDate) {
            // Skip loading slots and go directly to payment method
            $this->step = 4;
        }
    }
    
    public function updatedSelectedDate($value)
    {
        if ($value) {
            // Skip loading slots and go directly to payment method
            $this->step = 4;
        }
    }

    public function selectPaymentMethod($method)
    {
        Log::info('selectPaymentMethod called', ['method' => $method]);
        // Validate that the payment method is either 'cash' or 'online'
        if (!in_array($method, ['cash', 'online'])) {
            $this->addError('paymentMethod', 'Invalid payment method selected.');
            return;
        }
        
        $this->paymentMethod = $method;
        Log::info('About to call saveBooking', ['paymentMethod' => $this->paymentMethod]);
        // Automatically save the booking when payment method is selected
        $this->saveBooking();
    }

    public function saveBooking()
    {
        Log::info('saveBooking called', [
            'paymentMethod' => $this->paymentMethod,
            'selectedService' => $this->selectedService,
            'selectedDate' => $this->selectedDate,
            'numberOfPeople' => $this->numberOfPeople
        ]);
        // Validate that the payment method is either 'cash' or 'online'
        if (!in_array($this->paymentMethod, ['cash', 'online'])) {
            $this->addError('paymentMethod', 'Invalid payment method selected.');
            return;
        }
        
        // Set default times (9:00 AM to 10:00 AM)
        $startTime = '09:00';
        $endTime = '10:00';
        
        $this->referenceCode = Booking::generateReferenceCode();
        
        try {
            // Prepare booking data - only use customer_id since customer is logged in
            $bookingData = [
                'reference_code' => $this->referenceCode,
                'customer_id' => Auth::guard('customer')->id(),
                'service_id' => $this->selectedService,
                'booking_date' => $this->selectedDate,
                'start_time' => $startTime,
                'end_time' => $endTime,
                'status' => ($this->paymentMethod === 'cash') ? 'confirmed' : 'pending',
                'number_of_people' => $this->numberOfPeople,
                'payment_method' => $this->paymentMethod,
                'is_paid' => ($this->paymentMethod === 'cash') ? false : null, // For online payments, we'll set this after payment confirmation
            ];
            
            $booking = $this->bookingService->createBookingWithLock($bookingData);
            
            // The QR code is already generated by the model, so we just need to get it
            $this->qrCode = $booking->qr_code;
            
            // If payment method is cash, mark as confirmed
            if ($this->paymentMethod === 'cash') {
                $booking->update(['status' => 'confirmed']);
            } else {
                // For online payment, generate order reference
                $this->orderRef = 'ORD-' . strtoupper(uniqid());
                $booking->update(['order_ref' => $this->orderRef]);
            }
            
            $this->step = 5; // Show success and QR code
            Log::info('Booking created successfully, step set to 5', [
                'referenceCode' => $this->referenceCode,
                'qrCodeLength' => strlen($this->qrCode),
                'step' => $this->step
            ]);
        } catch (\Exception $e) {
            // Handle error
            Log::error('Booking creation failed', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString()
            ]);
            $this->addError('booking', 'Failed to create booking. Please try again. Error: ' . $e->getMessage());
            Log::error('Booking creation error: ' . $e->getMessage());
        }
    }

    public function render()
    {
        return view('livewire.create-booking');
    }
}